const fs = require("fs");

function addDivider() {
  return {
    type: "divider",
  };
}

function addSection(positions) {
  return {
    type: "section",
    text: {
      type: "mrkdwn",
      text: `*${positions[0].department}*`,
    },
  };
}

function addJobDescription(positions) {
  return {
    type: "section",
    text: {
      type: "mrkdwn",
      text:
        ">>>*<" +
        positions[0].positions[0].url +
        "| " +
        positions[0].positions[0].name +
        ">* \n" +
        "`📍 " +
        positions[0].positions[0].location +
        "`  |  `" +
        positions[0].positions[0].contract +
        "`",
    },
    accessory: {
      type: "button",
      text: {
        type: "plain_text",
        text: "Reffer a candidate \n",
        emoji: true,
      },
      style: "primary",
      value: "click_me_123",
    },
  };
}

function addEmptyLine() {
  return {
    type: "section",
    text: {
      type: "plain_text",
      text: "\n\n",
      emoji: true,
    },
  };
}

function displayPosition(positions) {
  const arr = [
    addDivider(),
    addSection(positions),
    addJobDescription(positions),
    addEmptyLine(),
  ];
  return arr;
}

exports.formatSlackMessage = (positions, company) => {
  const file = JSON.stringify({
    blocks: [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `✨ Opened positions at ${company} ✨`,
        },
      },
      {
        type: "context",
        elements: [
          {
            type: "plain_text",
            text: "\n",
            emoji: true,
          },
        ],
      },
      {
        type: "context",
        elements: [
          {
            text: "*January 12, 2021*  |  Generated by <https://www.hellotrusty.io/|Trusty>",
            type: "mrkdwn",
          },
        ],
      },
      {
        type: "context",
        elements: [
          {
            type: "plain_text",
            text: "\n",
            emoji: true,
          },
        ],
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "👋🏻 Hi {{firstName}}, \n\nEach Monday at 9am, you'll automatically receive *opened job positions* of your company. \n\nIf you know the *perfect candidate*, refer him/her.",
        },
      },
      {
        type: "context",
        elements: [
          {
            type: "plain_text",
            text: "\n",
            emoji: true,
          },
        ],
      },
      {
        type: "divider",
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "*Spontaneous refferal*",
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "You know a potential candidate that should join your company?\n\n📩 Make a spontaneous refferal. ",
        },
      },
      {
        type: "actions",
        elements: [
          {
            type: "button",
            text: {
              type: "plain_text",
              text: "Tell your company",
              emoji: true,
            },
            style: "primary",
            value: "click_me_123",
            action_id: "actionId-0",
          },
        ],
      },
      {
        type: "divider",
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "*Why referring?*",
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "💪🏻 As a collaborator, you are the best recruiting ambassador: \n\n You know your *companies values* and *work methods*. \n\n💼 By referring a potential employee from your network, it is a wager of trust. You can assure that your company is a *safe and pleasant* place to work\n\n✨ You participate in the building of a more cohesive and unified team. ",
        },
      },
      {
        type: "divider",
      },
      {
        type: "context",
        elements: [
          {
            type: "plain_text",
            text: "👋🏻 See you next week.",
            emoji: true,
          },
        ],
      },
    ],
  });

  fs.writeFile("output.json", file, function (err) {
    if (err) throw err;
    console.log("File is created successfully.");
  });
  return file;
};
